module edu.jhuapl.trinity {

    requires ch.qos.logback.classic;
    requires com.fasterxml.jackson.annotation;
    requires com.fasterxml.jackson.core;
    requires com.fasterxml.jackson.databind;
    requires com.github.trinity.supermds;
    requires commons.math3;
    requires eu.hansolo.fx.charts;
    requires fft4j;
    requires java.datatransfer;
    requires java.desktop;
    requires java.logging;
    requires java.naming; // needed by ch.qos.logback.classic
    requires java.net.http;
    requires java.prefs;
    requires javafx.controls;
    requires javafx.fxml;
    requires javafx.graphics;
    requires javafx.media;
    requires javafx.swing;
    requires jdk.crypto.ec;
    requires jdk.httpserver;
    requires jflac.codec;
    requires lit.litfx.controls;
    requires lit.litfx.core;
    requires org.apache.commons.lang3;
    requires org.apache.pdfbox.io;
    requires org.apache.pdfbox;
    requires org.fxyz3d.core;
    requires org.slf4j;
    requires org.zeromq.jeromq;
    requires quickhull3d;
    requires webcam.capture;

    opens edu.jhuapl.trinity to webcam.capture;
    opens edu.jhuapl.trinity.data to javafx.base;
    opens edu.jhuapl.trinity.data.graph to javafx.base;
    opens edu.jhuapl.trinity.data.terrain to javafx.base;
    opens edu.jhuapl.trinity.javafx.components.radial to lit.litfx.controls;
    opens edu.jhuapl.trinity.javafx.controllers to javafx.fxml;
    opens edu.jhuapl.trinity.javafx.javafx3d.particle to java.base;

    exports com.clust4j.algo.pipeline;
    exports com.clust4j.algo.preprocess.impute;
    exports com.clust4j.algo.preprocess;
    exports com.clust4j.algo;
    exports com.clust4j.data;
    exports com.clust4j.except;
    exports com.clust4j.kernel;
    exports com.clust4j.log;
    exports com.clust4j.metrics.pairwise;
    exports com.clust4j.metrics.scoring;
    exports com.clust4j.optimize;
    exports com.clust4j.sample;
    exports com.clust4j.utils.parallel.map;
    exports com.clust4j.utils.parallel;
    exports com.clust4j.utils;
    exports com.clust4j;
    exports edu.jhuapl.trinity.audio;
    exports edu.jhuapl.trinity.css;
    exports edu.jhuapl.trinity.data.audio;
    exports edu.jhuapl.trinity.data.cislunar;
    exports edu.jhuapl.trinity.data.coco;
    exports edu.jhuapl.trinity.data.files;
    exports edu.jhuapl.trinity.data.graph;
    exports edu.jhuapl.trinity.data.messages.bci;
    exports edu.jhuapl.trinity.data.messages.llm;
    exports edu.jhuapl.trinity.data.messages.xai;
    exports edu.jhuapl.trinity.data.messages;
    exports edu.jhuapl.trinity.data.terrain;
    exports edu.jhuapl.trinity.data;
    exports edu.jhuapl.trinity.icons;
    exports edu.jhuapl.trinity.javafx.components.annotations;
    exports edu.jhuapl.trinity.javafx.components.callouts;
    exports edu.jhuapl.trinity.javafx.components.hyperdrive;
    exports edu.jhuapl.trinity.javafx.components.listviews;
    exports edu.jhuapl.trinity.javafx.components.panes;
    exports edu.jhuapl.trinity.javafx.components.projector;
    exports edu.jhuapl.trinity.javafx.components.radial;
    exports edu.jhuapl.trinity.javafx.components.timeline;
    exports edu.jhuapl.trinity.javafx.components;
    exports edu.jhuapl.trinity.javafx.controllers;
    exports edu.jhuapl.trinity.javafx.events;
    exports edu.jhuapl.trinity.javafx.handlers;
    exports edu.jhuapl.trinity.javafx.javafx3d.animated;
    exports edu.jhuapl.trinity.javafx.javafx3d.images;
    exports edu.jhuapl.trinity.javafx.javafx3d.particle;
    exports edu.jhuapl.trinity.javafx.javafx3d.projectiles;
    exports edu.jhuapl.trinity.javafx.javafx3d.tasks;
    exports edu.jhuapl.trinity.javafx.javafx3d;
    exports edu.jhuapl.trinity.javafx.renderers;
    exports edu.jhuapl.trinity.messages;
    exports edu.jhuapl.trinity.utils.clustering;
    exports edu.jhuapl.trinity.utils.fun;
    exports edu.jhuapl.trinity.utils.loaders;
    exports edu.jhuapl.trinity.utils.metric;
    exports edu.jhuapl.trinity.utils.umap;
    exports edu.jhuapl.trinity.utils.volumetric;
    exports edu.jhuapl.trinity.utils.statistics;
    exports edu.jhuapl.trinity.utils;
    exports edu.jhuapl.trinity;
}
